### ISSUE TITLE
Create velocity vector length function and publish it to the bus.

### ISSUE THREAD

**Issue by bakotamas1997** [SzFMV2019-Osz/AutomatedCar-A#122]
A sebesség kimutatásához szükségünk lenne a sebességvektor hosszára. Kérlek számoljátok ki és publisholjátok a busra. Ennek az átszámolása egyáltalán nem tartozik a DashBoard feladatai közé, mivel az csak egy megjelenítés.

**Comment by pintergreg** [comment]
@bakotamas1997 Ez valóban nem a @SzFMV2019-Osz/team-a1 feladata, azonban számotokra csak egyetlen dolog szükséges, hogy egy előre ismert packet előre ismert adattagjában benne legyen, pontosabban, hogy legyen ilyen a buszon. Ha ti ezt kiolvassátok, akkor lényegében mindegy, hogy ők, írnak-e bele.

@SzFMV2019-Osz/team-a3 az elmozdulás vektor számolására utaló részeket láttam, de meghatározzátok a pillanatnyi sebességet is? Ők igazából azt kérik, hogy a műszerfalra ki tudják tenni, hogy az autó 150km/h-val süvít vagy 20-al botorkál.

Úgy általában véve elég gyérnek tűnik a két csapat közötti kommunikáció. Nekik van egy InputPacket-jük, amit éppen veletek akarnak integrálni #120. Mert, hogy nekik tőletek van szükségük a pedál- és kormányállásokra, hogy meg tudják határozni a pillanatnyi sebességet, többek között.
