### ISSUE TITLE
IWorld Interface + Alap funkciók

### ISSUE THREAD

**Issue by kaptast** [SzFMV2019-Osz/AutomatedCar-A#16]
World osztály bővítése
- addObject metódus: type (string), posx (int), posy (int), m11 (int), m12 (int), m22(int), m23 (int)), ad a worldObjects collectionbe egy új worldObjectet a hasonló konstruktorán keresztül, megvalósítva: #18
- implements IWorld

IWorld interface (package: model/interface)
- getWidth
- getHeight
- getColor

**Comment by pintergreg** [comment]
@kaptast Értem a logikát a [A2nnn] kódolás mögött, de légy szíves inkább ne. GitHubon is minden issue kap id-t ez speciel a 16-os és a GH markdown segítségével linkelni is lehet őket pl. #18. Commit üzenetben is működnek ezek a linkek. Ezt használva _valóban_ összekötésre kerülnek a dolgok.
Az [A2] és [S1] kódokkal semmi bajom, sőt kifejezetten hasznosak tudnak lenni adott esetben, de miután az issue hivatkozásra van beépített, működő megoldás szerintem inkább azt kellene használni.

**Comment by kaptast** [comment]
@pintergreg A logika mögött @deseatnikov áll. A Projects és a Milestone hivatkozásokat beállítottuk így szerintem az [A2] [S1] kódok se feltétlen szükségesek.

**Comment by deseatnikov** [comment]
Átírom még ma

**Comment by sandor95** [comment]
Átnéztem én is a PR-t, kiszúrtam egy fontos dolgot, lehet, hogy sok mindent fog érinteni, valószínűleg refaktorálni kell még 1-2 objektumot.

**Comment by deseatnikov** [comment]
Igen, #27 és #28-ban lesz majd kiszervezés innen, jelenleg csak kell egy alap amire meg lehet csinálni az XML parseot

**Comment by deseatnikov** [comment]
+WorldObject bővítése, majd a pull requesten látszik
