### ISSUE TITLE
Kamera szenzor egyeztetés

### ISSUE THREAD

**Issue by deseatnikov** [SzFMV2019-Osz/AutomatedCar-A#163]
Lényegében a WorldManagerben már van háromszöges lekérdezés (a poligonos PR-ben jó is lesz). Ennek használatát kell majd átbeszélni @SzFMV2019-Osz/team-a4 -el.

**Comment by deseatnikov** [comment]
#171

**Comment by pintergreg** [comment]
Apró megjegyzés: le lett zárva ez az issue, ami arról szólt, hogy egyeztetni kell valamiről. Az elegáns és _követhető_ az lenne, ha lezáráskor pár mondatban össze lenne foglalva, hogy mi lett az egyeztetés eredménye.

**Comment by deseatnikov** [comment]
Azért lett lezárva mert a #171 is erről szól és ez duplicate
