### ISSUE TITLE
CrashListener

### ISSUE THREAD

**Issue by deseatnikov** [SzFMV2019-Osz/AutomatedCar-A#165]
Preconditions:
- [x] #164 metódus szignatúra egyeztetés

Task:
- [ ] CrashListener megírása ami a preconditionben egyeztetett szignatúrával ellátott metódussal rendelkezik: "Legyen egy új object: CrashEventParams üresen a model.utility-ben, ez legyen az egyetlen paramétere a listener metódusnak és akkor szabadon állítgathatjuk majd mi megy át eseménnyel"
- [ ] WorldManager kiegészítése egy CrashListenerrel
- [ ] CrashListener feliratkoztatása minden ICrashable objectre (meg lesz csinálva #183-ban)
- [ ] Megvalósítás, hogy mi történik az eseménykor (popup dobás)

**Comment by deseatnikov** [comment]
Legyen egy új object: CrashEventParams üresen a model.utility-ben, ez legyen az egyetlen paramétere a listener metódusnak és akkor szabadon állítgathatjuk majd mi megy át eseménnyel

**Comment by sandor95** [comment]
> Preconditions:
> 
> * [x]  #164 metódus szignatúra egyeztetés
> 
> Task:
> 
> * [ ]  CrashListener megírása ami a preconditionben egyeztetett szignatúrával ellátott metódussal rendelkezik: "Legyen egy új object: CrashEventParams üresen a model.utility-ben, ez legyen az egyetlen paramétere a listener metódusnak és akkor szabadon állítgathatjuk majd mi megy át eseménnyel"
> * [ ]  WorldManager kiegészítése egy CrashListenerrel
> * [ ]  CrashListener feliratkoztatása minden ICrashable objectre (meg lesz csinálva #183-ban)
> * [ ]  Megvalósítás, hogy mi történik az eseménykor (popup dobás)

Egy kicsit máshogy lett megvalósítva, mert javaban úgy tudom nincsenek a C#-ban megszokott delegáltak, de nem vagyok benne biztos. Ezért inkább csináltam egy CrashExceptiont és azzal kezelem az ütközést.
