### ISSUE TITLE
XML parse

### ISSUE THREAD

**Issue by deseatnikov** [SzFMV2019-Osz/AutomatedCar-A#17]
XmlParser (package: xml). Feladata az XML beolvasása és objektumok gyártása.

Definition of Done:

- [x]  _double_ és _int_ converterek implementálása
- [x]  kapott fájlnév validálása, kiegészítése kiterjesztéssel ha szükséges
- [x]  XML feldolgozása, objektumok létrehozása és elhelyezése a _Worldbe_
- [x]  _World_ visszaadása
- [x]  hibakezelés kialakítása, értelmes üzenetet adjon vissza, ami meg is jeleníthető

**Comment by deseatnikov** [comment]
TODO discuss: roadpainting_1...3, scene measureType mik akarnak lenni

**Comment by pintergreg** [comment]
> TODO discuss: roadpainting_1...3, scene measureType mik akarnak lenni

@deseatnikov @SzFMV2019-Osz/team-a2  Az út felfestéseit kódolják, pl. folytonos záróvonal, meg -nem tudom a hivatalos nevét- előzést is megengedő, szaggatott sávelválasztó vonal.

Korábban tervben volt, hogy a feladat során használni kell, de a jelenlegi feladatkiosztásban nyugodtan ignorálhatjátok. Semmilyen későbbi feladat nem épít rá. (Ráadásul azt hiszem néhány helyen hibásan is van felvéve.)

**Comment by pintergreg** [comment]
@SzFMV2019-Osz/team-a2 A Scene-ben a measureType is fölösleges. 

Ezen kívül kimaradt a repóból, de van egy nagy méretű világ állomány is: https://raw.githubusercontent.com/SzFMV2019-Osz/handout/master/src/resources/test_world_1kmx1km.xml

A kicsin jóval egyszerűbb debuggolni, javasolt azzal kezdeni.

**Comment by sandor95** [comment]
Elkészült az xml parser, van egy olyan érzésem, hogy nem elég gyorsan dolgozik (300 soros xml ~ 800 ms, 5000 soros xml ~ 2.5-3,0 sec), csinálok hozzá egy külön issue-t, amiben majd jobban megnézem, mert van tippem mi tart sokáig.

**Comment by sandor95** [comment]
Mivel nagyon bosszantott ez a lassúság, megcsináltam gyorsan még ebbe a brancbe. :)
