### ISSUE TITLE
[S2] - Radar háromszög interakció a megjelenéssel

### ISSUE THREAD

**Issue by arminro** [SzFMV2019-Osz/AutomatedCar-A#171]
DoD:
- [x] a háromszög dimenziói nem változnak, de helyzete folyamatosan frissül
- [x] ki/és bekapcsolási leheőség + adott szín
- [x] a látószög static 60°
- [x] a radarháromszög magasságának távolsága static 200m

**Comment by arminro** [comment]
HelpWanted: 
A sprint 2 leírásban (https://github.com/SzFMV2019-Osz/AutomatedCar-A/issues/8)
egyszer az szerepel, hogy legyen fixen piros, egyszer meg az, hogy  a szín legyen bekérhető.

**Comment by pintergreg** [comment]
@arminro A team4-től azt kértem, hogy úgy implementálja a háromszög rajzolást, hogy a szín paraméterezhető legyen, mert a szenzoroknak külön színnel kell szerepelnie. Például a radar piros. De ez a user story csak felhasználja az előzőben definiált API-t.

**Comment by deseatnikov** [comment]
Szenzorokra rakjunk set-get colort?

**Comment by deseatnikov** [comment]
És akkor elég nektek ezt beállítani és majd csak innen szeditek ki ahelyett, hogy valami random helyen levő változó lenne

**Comment by pintergreg** [comment]
@deseatnikov Elnézést, hogy csak most válaszolok. A szenzorra nem kell set/get color. Szerintem több mint elegendő, ha a szenzor debug színe bele van égetve  kódba, miután az, hogy a radar pirossal legyen kirajzolva a feladatból (megrendelői igényből) ered.

Én ezt úgy képzelem, hogy a szenzoron belül van egy konstans ami tárolja a színt, amikor a látóteret vizualizálni kell és meghívásra kerül a Sprint 1-ben implementált metódus, akkor oda átadásra került ez a (pl.) RadarSensor osztályban privát adattagként letárolt szín.

**Comment by deseatnikov** [comment]
Akkor csak getColor lesz, és az be lesz égetve, úgy jó? Mondjátok milyen szín kell

**Comment by deseatnikov** [comment]
Radar default range akkor hány pixel legyen?

**Comment by deseatnikov** [comment]
A WorldManagerben majd lesz egy moveCar ami mozgatja a kocsit és vele együtt az összes rászerelt szenzort
