### ISSUE TITLE
Planning test coverage

### ISSUE THREAD

**Issue by deseatnikov** [SzFMV2019-Osz/AutomatedCar-A#23]
Tesztesetek írása.

TODO: kitalálni mikre akarunk teszteseteket, XML-re biztos (test_world és lane_keeping_test_world-re is menjen)

**Comment by sandor95** [comment]
> Tesztesetek írása.
> 
> TODO: kitalálni mikre akarunk teszteseteket, XML-re biztos (test_world és lane_keeping_test_world-re is menjen)

- Az XML parseoláshoz kellenek majd converterek, azokhoz is kell majd teszt.
- Rotáció számolás is egyszerűen unit tesztelhető
