### ISSUE TITLE
WorldManager - mások ezt fogják használni

### ISSUE THREAD

**Issue by deseatnikov** [SzFMV2019-Osz/AutomatedCar-A#29]
package: model/manager

private World currentWorld

> IWorld initWorld (string xmlPath)
> - XMLParser.parseXML
> - eredmény kimentése currentWorld-be
> - return (IWorld) currentWorld
> (itt a return nem kell, ha akik meghívják nem mentik ki -> **egyeztetni**)

#50

- [x] validate kivétele, konstruktorba mozgatás miatt

~~IWorld getWorld() implementáció~~ - nem szükséges

- [x] List\<IObject\> getAllObjects() implementáció

- [x] List\<IObject\> getAllObjectsInTriangle implementáció

**Comment by sandor95** [comment]
Ezzel kapcsolatban van 1-2 meglátásom, csütörtökön megbeszélhetnénk.

**Comment by deseatnikov** [comment]
initWorld -> konstruktor

**Comment by sandor95** [comment]
Ezt nem lehetne összemergelni issue #50-el?
