### ISSUE TITLE
Javadoc

### ISSUE THREAD

**Issue by deseatnikov** [SzFMV2019-Osz/AutomatedCar-A#31]
Javadoc átnézése/kiegészítése/megírása a finalban levő dolgokhoz

**Comment by deseatnikov** [comment]
Ez most folyamatosan aktív, minden egyes új feature-el javul a javadoc egy kicsit :)

**Comment by pintergreg** [comment]
@deseatnikov Ez a stale bot nagyon primitív, akkor próbálja felrázni az állóvizet ha egy hétig nem volt aktivitás az issue-n. Elvileg elkerülhető akkor ha a vonatkozó commit üzenetekbe be van hivatkozva az issue. (Akár több issue is hivatkozható, pl.: Implement foobar #id1 #id2)

Másrészt ez a taszk is olyan mint a tesztírás, igazából a feature-el együtt kellene mennie, külön ernyőissue nélkül is.

**Comment by deseatnikov** [comment]
Jó lenne megoldani a javadocot most már véglegessé, akinek van ideje az csinálhat erre branchet és végigmehet az összes osztályon. Még ha a final részek nincsenek is készek, most már végre mindenkinek van ötlete arról, hogyan fog felépülni az első sprint és így nem olyan javadocot írunk amit háromszor át kell írni

Jó lenne ezt lezárni refaktor előtt

**Comment by deseatnikov** [comment]
Ez már nem issue
