### ISSUE TITLE
Kód refaktor/kiegészítés az első sprintben érintett dolgokhoz

### ISSUE THREAD

**Issue by deseatnikov** [SzFMV2019-Osz/AutomatedCar-A#32]
Ahol szükséges, közös átnézése/átbeszélése a dolognak és a követelményeknek, hogy mindennel megvagyunk-e mielőtt befejezettnek jelentjük ki a sprintet, ha kell még dolgozni akkor a final milestonet bővítjük kimaradt funkciókkal

**Comment by sandor95** [comment]
Az XML parse-nál lesz egy giga refakt, minden primitív típust át kell majd írnom a neki megfelelő osztályra, mert a JAXB csak osztályokkal tud dolgozni. Ezt majd persze megcsinálom én, ne is nyúljatok bele légyszi, mert a giga refakt mellé kaptok egy giga conflictot is :D

**Comment by pintergreg** [comment]
@sandor95 Ez most abszolút szakmai kíváncsiság, mivel nem ismerem a JAXB-t, de nem tudsz olyan modell osztályt használni, ahol a primitív típusok vannak benne? pl.
```java
class foo {
    int a;
    float b;
}
```
Hanem át kell írni az `int`-et `Integer`-re, vagy hogy érted, hogy csak osztályokkal tud dolgozni?

**Comment by sandor95** [comment]
> @sandor95 Ez most abszolút szakmai kíváncsiság, mivel nem ismerem a JAXB-t, de nem tudsz olyan modell osztályt használni, ahol a primitív típusok vannak benne? pl.
> 
> ```java
> class foo {
>     int a;
>     float b;
> }
> ```
> 
> Hanem át kell írni az `int`-et `Integer`-re, vagy hogy érted, hogy csak osztályokkal tud dolgozni?

Eddig csak olyan kóddal találkoztam, ahol osztályok voltak a változók, de utánanézek, hátha meg lehet oldani. A probléma az, hogy XmlAdapter osztályokkal konvertálja át a stringet nekünk tetsző értékre, ami csak objektumokat tud kezelni, bár lehet rosszul tudom.

**Comment by sandor95** [comment]
Egyelőre úgy tűnik, hogy meg lehet oldani (köszönöm a kérdést, ebbe bele se gondoltam! :) ), csak ügyesen kell felannotálni a modelleket. Ha bekerül issue #33 PR, akkor már neki is esek, hogy minél előbb kiderüljön, hogy tényleg minden oké-e.

**Comment by sandor95** [comment]
#51-ben helyeztem/helyezek el TODO-kat, amiket majd a refaktor során megcsinálhatnánk. Azért nem abba a branchbe csinálom, mert nem oda tartozik a refakt.

**Comment by sandor95** [comment]
ObjectConverter-re és ReferenceConverter-re kellenének direkt tesztek, csak közvetve vannak tesztelve, XmlParseren keresztül. Ezek nem olyan egyszerűek, több függőség is van, ezért kiemelem ide.

**Comment by deseatnikov** [comment]
> #51-ben helyeztem/helyezek el TODO-kat, amiket majd a refaktor során megcsinálhatnánk. Azért nem abba a branchbe csinálom, mert nem oda tartozik a refakt.

A fájl beolvasós spottolása ügyes volt, minél kevesebb dolog legyen megírva kétszer
