### ISSUE TITLE
Vector model létrehozás

### ISSUE THREAD

**Issue by tothnorbert97** [SzFMV2019-Osz/AutomatedCar-A#37]
@SzFMV2019-Osz/team-a2 

Szükségünk lenne egy Vector model-re, amivel az okjektumok elmozdulását tudnánk reprezentálni.
A Vector model-nek a következőket kéne tartalmaznia:

- [ ] pozíció (Position - már implementálva van), az elmozdulás irányát jelzi (get,set)

- [ ] hossz (lebegőpontos szám), az elmozdulás mértékét jelzi (gyorsulás) (get,set)

Kéne egy konstruktor hozzá, amely bekéri a fent említett paramétereket.

**Comment by pintergreg** [comment]
És ne felejtsük el, hogy szükség van vektor algebrára is. Mármint vektorokat össze kell tudni adni, kivonni (hirtelen nem tudom, hogy ennél kell-e sokkal több minden).
Meg azt sem árt észben tartani, hogy nem kell újra feltalálni a kereket. :wink:

**Comment by deseatnikov** [comment]
Vektor algebrát majd maven dependencyvel be tudnátok húzni valahonnan (így is van most sok dolgunk aztán könnyebb és gyorsabb lenne egy mvn clean install keresgélés helyett)? (Engedélyezett a tárgy keretében mavennel behúzogatni dolgokat?) 

A vector model melyik teamnek kell? Muszáj azt modelként/modelben megvalósítani? **Interface kell csak?** Kis pontosítást megköszönnénk, hogy mit is akartok és ehhez miért mi kellünk :D (Ha pl. csak megjelenítéshez tartozik akkor nem biztos, hogy ezt nálunk kell használni. A legkönnyebb, ha úgy írnád le nekünk mintha 5 évesek lennénk.)

Ha vannak kapcsolódó issuek, azokat is leírhatnátok a válaszba #szám-al, köszi.

**Comment by tothnorbert97** [comment]
Szerintem a "nem kell újra feltalálni a kereket" rész is erre célozhatott, hogy ezt fel tudjuk használni máshonnan is. Az alap gondolatmenet abból fakadt, hogy a projekt tartalmaz már egy Positon nevű osztály. Ez lehetséges, hogy később kapcsolatba kerül majd a Vector egyes elemeivel (lehet ez csak az én agyam szüleménye), ezért gondoltam mindenféle átadogatás, konvertálgatás nélkül egyszerűbb lenne megoldani. A felvetés viszont jogos, használatba veszünk majd egy már korábban megírt Vector-t (kivéve ha a többiek máshogy látják).

**Comment by deseatnikov** [comment]
Szerintem beszéljétek majd meg közösen, hogy mi is legyen pontosan és ha van egy kiforrott ötlet majd ha tényleg kellünk hozzá akkor pingeljetek meg minket újra :) Amúgy pedig nem rossz ötlet amit felhoztál, készül éppen Position osztály a modelben, szóval nyitott vagyok rá, csak konkrétum kell ha ebben maradtok, hogy tudjuk mit kelljen lekódolni

**Comment by pintergreg** [comment]
@deseatnikov 
> Engedélyezett a tárgy keretében mavennel behúzogatni dolgokat?

Igen, (valahol megemlítem a jegyzetben is, de) természetesen bármely maven-nel elérhető lib használható, ami Java 11-el kompatibilis. Az Apache math körül is akad szerintem vektor implementáció, bár ezt most csak érzésre írtam.

@tothnorbert97 
> Szerintem a "nem kell újra feltalálni a kereket" rész is erre célozhatott, hogy ezt fel tudjuk használni máshonnan is.

Így van. 
(Ugyanakkor volt olyan félév is, amikor írtak egy minimalista "Vector2D" osztályt és azt a pár metódust implementálták ami pl. egy eredőszámításhoz kellett nekik.)
