### ISSUE TITLE
[S1] - Selected Object

### ISSUE THREAD

**Issue by Greg-Kovacs** [SzFMV2019-Osz/AutomatedCar-A#44]
Provide an interface, so that the polygon of a selected object appears with a different color.

How do we define selected? : Good question, will investigate @ class

**Comment by pintergreg** [comment]
> How do we define selected? : Good question, will investigate @ class

Kis segítség: az objektumról tudnod kell, hogy ki van-e jelölve vagy sem: `private boolean selected` mező. Nyilván getter/setter is kell, mert nektek le kell tudnotok kérdezni, a szenzornak meg be kell tudnia állítani. Ebből máris következik egy kérés a modell csapat irányába, hogy az objektumoknak legyen `selected` attribútuma.

És így tovább...
