### ISSUE TITLE
Hajtáslánc Tervek/Dokumentáció

### ISSUE THREAD

**Issue by Petyaaaa5** [SzFMV2019-Osz/AutomatedCar-A#47]
-Be - kimenetek
-Minimális dokumentáció

DIAGRAM (v2):
![PowertrainV2](https://user-images.githubusercontent.com/55531206/66209647-1871e880-e6b8-11e9-9dd3-dca2b012f2bd.png)

**Comment by Petyaaaa5** [comment]
Diagram Drive link:
https://drive.google.com/open?id=14iZchVFljTeHDhFaUbFqOsQ4kj2xzhtR

**Comment by tothnorbert97** [comment]
@pintergreg A fentebbi drive-os linken updatelve lett a diagramunk az előző órán (2019. október 3.) megbeszéltek szerint (amit megértettünk belőle). Esetleg rá tudnátok vetni egy pillantást és egy visszajelzést adni, hogy körülbelül jó úton indultunk-e el?

**Comment by pintergreg** [comment]
@tothnorbert97 @SzFMV2019-Osz/team-a3 Nekem kifejezetten tetszik ez a folyamatábra.

## váltó
Amit hiányolok az a belső fokozatok fordulatszámra gyakorolt hatása. Ugye belül váltasz, de váltáskor visszaesik a fordulatszám, kb így:

![](http://efi.moonwell.com/gears-graph.php?rpm=6000&mph=55&r1=3.58&r2=2.02&r3=1.35&r4=0.98&r5=0.69&r6=0&fdr=3.94&diameter=25&trans=Getrag%20F23%205%20Speed)

Nem tudom honnan van ez a kép, nem a legrealisztikusabb, de remekül látszik a visszaesés és az, hogy magasabb fokozaton lassabban éri el újra a váltási fordulatszámot.

## lassítás

Kicsit túlzásak érzem, hogy többféle lassító erő van. Elég egy, amire simán rá lehet fogni, hogy benne van a légellenállás, a súrlódás meg minden egyéb. Tehát a gördülési ellenállás szerintem kidobható. Nem kell ennyire belemenni.

## kormányzás

> Kormányállás korlátozása a fordulási szögtartományba

Ez fontos, hogy van! Ez kb. az áttét a kerekek és a kormány között. Egy valóságos kormány többször körbetekerhető, itt most ettől eltekintünk, ezért van a -100,100 dolog, így kevésbé tűnik ki de kell.

_Előre elnézést, ha túl szájbarágós lesz, de nem tudom ki mit nem ért és milyen előzetesismeretei vannak._

A fordulókör _nektek kell_ a végző vektor meghatározásához. A ti komponenseteket sosem hagyja el enne, de anélkül nem lehet realisztikus kanyarodást implementálni. Nem tudom kinek van köztetek jogsija, de gondolj bele: megy az autó egyenesen, eltekered a kormányt jobbra (pl.), az autó hátulja nem fog elshiftelődni jobbra (tükörjégen megcsúszás meg hasonló dolgokat hagyjuk). Az első kerekek befordulnak jobbra, de közben az autó még előre halad (is) halad és csak szépen lassan kezd el jobbra kitérni mintha egy _nagy_ körön mozogna. A kör nagysága a sebességtől függ. Kisebb sebességnél kisebb, pl megfordulsz az udvaron gyök kettővel, de az 100-al csak egy óriási körben tudnál megfordulni.

Tehát olyan ez mintha az autó forgatási pontja az autón kívülre esne. Ezt mutatja ez az ábra:
![](https://i.stack.imgur.com/DQsP9.png)

A fordulókör sugarának kiszámításához a [jegyzetben](https://szfmv2019-osz.github.io/handout/physics.html#kanyarod%C3%A1s) linkelt forrás képletét használom:

> atan(wheelbase / (turning circle - car width)) = angle

A [`car_2_white.png`](resources/car_2_white.png) esetében a szélesség kb. 90px, a tengelytáv kb. 130px-nek tekinthető. Tegyük fel, hogy maximum 60°-ban kormányozható, ekkor a fordulókör sugara:

> - atan(130px / (r - 90px)) = 60°
>
> - tan(60) = 130/(r-90)
> - r = 130/tan(60) + 90
> - r = ~165px

Ekkor megvan, hogy mely pont körül fordul az autó. Egy ciklusban (40ms) mindig ki kell számolni, hogy a pillanatnyi sebesség és kormányállás következtében az előző ciklus mozgásvektora hogyan fog módosulni. 

És ugye az autó mint kép forgatását is meg kell határozni, de nem az autó bal felső sarka körül kezded el forgatni, hanem a fentinek megfelelően, hogy ne csak az vektorod legyen realisztikus, hanem a megjelenése is. 

Az AutomatedCar osztályba visszaírni csak az x,y koordinátát és az elforgatást kell (adott referencia pont körül). Jelenleg a modell a 0,0 pont körüli forgatást feltételezi, mivel ti nem rendelkeztetek másképp és azzal az értékkel van kitöltve a megfelelő adattag. Arra is át lehet amúgy számolni az egészet.
A megjelenítés csapat csak annyit fog csinálni, hogy egy adott referencia pont körül értelmezik a megadott elforgatását az autó képének, az adott pozícióba.

De itt például a kanyarodás leprogramozásához egyéb minta is van: http://www.asawicki.info/Mirror/Car%20Physics%20for%20Games/Car%20Physics%20for%20Games.html
