### ISSUE TITLE
WorldManager - Objektumlekérdezések

### ISSUE THREAD

**Issue by zeatrun** [SzFMV2019-Osz/AutomatedCar-A#50]
Függvények írása ami:
- [x] Visszaadja az objektumokat egy pont helyéről (1 bemeneti pont)
- [x] Visszaadja az objektumokat egy négyzet területről (2 bemeneti pont)
- [x] Visszaadja az objektumokat egy háromszög területéről (3 bemeneti pont)

--------- addition 
- [x] initWorld konstruktorba mozgatása

**Comment by deseatnikov** [comment]
initWorld helyett konstruktorban lesz az inicializálás majd @SzFMV2019-Osz/team-a4

**Comment by deseatnikov** [comment]
A négyzet az alábbi módon fog kinézni: pont3: pont1 x, pont2 y; pont4: pont 1 y, pont 2 x

Jó lesz? @SzFMV2019-Osz/team-a4

**Comment by deseatnikov** [comment]
Még várjátok meg a merget
