### ISSUE TITLE
Reference position beolvasás

### ISSUE THREAD

**Issue by deseatnikov** [SzFMV2019-Osz/AutomatedCar-A#51]
DoD:

- [x] XMLParser bővítése references xml beolvasással (amelyik nem szerepel az xml-ben annak 0,0 a referencepoint)

- [x] IObject-be getReferenceX és getReferenceY

- [x] Position eltárolása a WorldObjectekben

- [x] Referencia pontok áttöltése a WorldObjectekbe

@SzFMV2019-Osz/team-a4

Minden IObjectnek lesz egy `getReferenceX()` és egy `getReferenceY()` metódusa, mindkettő `int`-et fog visszaadni. Ez így jó lesz vagy kényelmesebb lenne nektek ha `Position` objektumot adnánk át?

**Comment by deseatnikov** [comment]
todo obect szűrést kitalálni, hogy reference pointokkal vagy x,y-okkal működjön, megbeszélés

**Comment by sandor95** [comment]
Ha #57 merged, akkor nekiállok ennek. Amíg nincs bent, addig fölösleges elkezdeni, mert csak conflictok lesznek.

**Comment by sandor95** [comment]
Azt hiszem help needed! 😞 

Bármiféle kapcsolat van a test_world-ből beolvasott objektumok és a reference_points-ből beolvasandó értékek között? Netán teljesen különálló adatok? Esetleg csak át kell adni a megjelenítésnek a reference pontokat?

@pintergreg , @deseatnikov , @kaptast ?

**Comment by kaptast** [comment]
@sandor95 Közvetlen kapcsolat nincs köztük. A reference_points-ben az van definiálva hogy a kép kirajzolásához képest hol van az objektum tényleges (xmlből beolvasott) pozíciója. Tehát ha vsn egy objektumunk a 10,10 pozícióban a referencesben is 10,10 áll akkor a 0,0 pozícióra kell rajzolni az objektum képét. Szerintem amúgy elég ha csinálsz egy referencePoint nevű változó és kitöltöd az X, Y-ját a megfelelő típusoknak. Ami nincs benne az xml-ben ott 0,0 a referencia pont.

**Comment by deseatnikov** [comment]
> @sandor95 Közvetlen kapcsolat nincs köztük. A reference_points-ben az van definiálva hogy a kép kirajzolásához képest hol van az objektum tényleges (xmlből beolvasott) pozíciója. Tehát ha vsn egy objektumunk a 10,10 pozícióban a referencesben is 10,10 áll akkor a 0,0 pozícióra kell rajzolni az objektum képét. Szerintem amúgy elég ha csinálsz egy referencePoint nevű változó és kitöltöd az X, Y-ját a megfelelő típusoknak. Ami nincs benne az xml-ben ott 0,0 a referencia pont.

Eszerint módosítom a leírás második pontját

**Comment by deseatnikov** [comment]
Átírtam kicsit a pontokat és 2-ből 4 lett.

**Comment by deseatnikov** [comment]
Gyors ötlet: alapból 0,0 a reference get worldobjectben
Ahol pedig az XML mondja ott overrideolják az alaposztályok (pl.: car, road), a specifikusok pedig tovább overrideolhatják azokat is majd
Ha nem lehet XML parseal kényelmesen megoldani (pl temp osztállyal akár) akkor elég behardcodeolni ezeket, bár az nem olyan elegáns

**Comment by deseatnikov** [comment]
Ezalatt értem, hogy lesz egy osztály ahol van type-érték és lényegében ezek közül ad vissza majd az overrideolt get, mintha beolvasott konstansok lennének

A hardcode alatt pedig azt értem, hogy bevágod őket a consts values részbe REFERENCE_[TYPE] név alatt

**Comment by sandor95** [comment]
> @sandor95 Közvetlen kapcsolat nincs köztük. A reference_points-ben az van definiálva hogy a kép kirajzolásához képest hol van az objektum tényleges (xmlből beolvasott) pozíciója. Tehát ha vsn egy objektumunk a 10,10 pozícióban a referencesben is 10,10 áll akkor a 0,0 pozícióra kell rajzolni az objektum képét. Szerintem amúgy elég ha csinálsz egy referencePoint nevű változó és kitöltöd az X, Y-ját a megfelelő típusoknak. Ami nincs benne az xml-ben ott 0,0 a referencia pont.

Kiegészíteni nem tudom a már elkészült objektumokat, szóval ezeket külön listába kell majd betölteni és összepárosítani. Ha jól értem, akkor lényegében a reference_points-ban található Image name az, ami összeköti a test_world-ben lévő Object type-jával? Ha ez így van, akkor alakítani kell a kép betöltésen/fájlnév generáláson, mert pl a nagy xml-ben olyan typeok is vannak, amik nem képfájlok nevei.


@deseatnikov, amiket írtál, majd átgondolom, ha végre kitisztul előttem a kép, hogy mit is kell majd csinálni. Azt az opciót fogom választani, ahol kevesebbet kell majd kódolni, dolgozzanak majd az annotációk, meg a JAXB. :D

**Comment by kaptast** [comment]
> 
> 
> > @sandor95 Közvetlen kapcsolat nincs köztük. A reference_points-ben az van definiálva hogy a kép kirajzolásához képest hol van az objektum tényleges (xmlből beolvasott) pozíciója. Tehát ha vsn egy objektumunk a 10,10 pozícióban a referencesben is 10,10 áll akkor a 0,0 pozícióra kell rajzolni az objektum képét. Szerintem amúgy elég ha csinálsz egy referencePoint nevű változó és kitöltöd az X, Y-ját a megfelelő típusoknak. Ami nincs benne az xml-ben ott 0,0 a referencia pont.
> 
> Kiegészíteni nem tudom a már elkészült objektumokat, szóval ezeket külön listába kell majd betölteni és összepárosítani. Ha jól értem, akkor lényegében a reference_points-ban található Image name az, ami összeköti a test_world-ben lévő Object type-jával? Ha ez így van, akkor alakítani kell a kép betöltésen/fájlnév generáláson, mert pl a nagy xml-ben olyan typeok is vannak, amik nem képfájlok nevei.
> 
> @deseatnikov, amiket írtál, majd átgondolom, ha végre kitisztul előttem a kép, hogy mit is kell majd csinálni. Azt az opciót fogom választani, ahol kevesebbet kell majd kódolni, dolgozzanak majd az annotációk, meg a JAXB. :D

Egy JAXB-vel betöltött objektumot nem tudsz később kiegészíteni egy másik beolvasással? 
Ha nem lehet akkor vagy írunk egy ronda ciklust és feltöltögetjük az elemeket egyesével, vagy tényleg egy listába (Hash dictionary?) töltjük be és minden lekérdezésnél elkérjük a listától, ez viszont lassú lehet. Valakinek valamilyen más ötlet?

**Comment by sandor95** [comment]
> Egy JAXB-vel betöltött objektumot nem tudsz később kiegészíteni egy másik beolvasással?
> Ha nem lehet akkor vagy írunk egy ronda ciklust és feltöltögetjük az elemeket egyesével, vagy tényleg egy listába (Hash dictionary?) töltjük be és minden lekérdezésnél elkérjük a listától, ez viszont lassú lehet. Valakinek valamilyen más ötlet?

Nem, sajnos nem ilyen egyszerű a dolog (legalábbis nem tudok róla, hogy ilyenre képes lenne). Igen, a ciklusos megoldás lenne majd. A HashMap jó ötlet, lehet egyenest abba kell majd betölteni a reference pointokat.

A kérdéses pont tehát a test_world - Object - type ~= reference_points - Image - name?

**Comment by pintergreg** [comment]
> Azt hiszem help needed! disappointed
> 
> Bármiféle kapcsolat van a test_world-ből beolvasott objektumok és a reference_points-ből beolvasandó értékek között? Netán teljesen különálló adatok? Esetleg csak át kell adni a megjelenítésnek a reference pontokat?

A referencia pont a transzformációra vonatkozik. A road_2lane_90left.png 525x525 méretű, de a 90 fokos balkanyar forgatási pontja nem a 0,0, hanem az x=175 y=525, tehát ez a pont: 
![](https://szfmv2019-osz.github.io/handout/images/90left.png)

A transzformációs mátrixban leírt forgatás, arra a pontra vonatkozik. A rajzoló csapat akkor tudja összeilleszteni az elemeket, ha tudja, hogy mely pont körül kell forgatnia. Nektek elegendő csak letárolni ezt az értéket.

Az a megoldás nagyszerű, hogy ez a pont 0,0 kivéve ha a reference_points.xml másképp nem rendelkezik. Még egy kivétel van, az a vezérelt autó. Mivel az autó mozgatásáért felelős csapat (@SzFMV2019-Osz/team-a3 ) még nem tart ott az implementációban, nem fogalmazódott meg bennük az az igény, hogy az AutomatedCar esetében esetleg ne a 0,0 legyen a forgatási pont. Elvileg azzal is megoldható, de általában mást szoktak használni. A ti szempontotokból egyelőre maradhat az is 0,0.

**Comment by sandor95** [comment]
> todo obect szűrést kitalálni, hogy reference pointokkal vagy x,y-okkal működjön, megbeszélés

Ez ha minden igaz, már meg lett beszélve, hogy Position-ök alapján kérdezik le az objektumokat
