### ISSUE TITLE
Poligonok definiálása

### ISSUE THREAD

**Issue by deseatnikov** [SzFMV2019-Osz/AutomatedCar-A#52]
- [x] type alapján poligonok definiálása
- [x] type alapján z indexek definiálása 

Legyen ModelCommonUtilban egy metódus ami beállítja ezeket, hogy csak ott kelljen átírni és ne osztályonként ha valami változik

**Comment by deseatnikov** [comment]
Hozzáadom ide a Z-indexek kitalálását is

**Comment by deseatnikov** [comment]
Azóta gondolkoztam ezen egy kicsit és ha java.awt Shapeket használunk ott van egy intersects method amivel nagyon könnyen meg tudjuk nézni, hogy overlappolnak-e a leadott négyzettel 

Ehhez minden objektumnak lehet egy ShapeListje ami egytől x mennyiségű shapet tartalmaz és ez adja a poligont (azért nem csak egy mert útnál pl 3 vonal)

**Comment by deseatnikov** [comment]
But that’s just a theory

**Comment by pintergreg** [comment]
@deseatnikov Szerintem nincs. Midig ezt szokták használni, főleg mivel én órán ki is szoktam emelni, hogy ott van a java.awt[...]geometry névtér amivel ez módfelett kényelmesen megoldható. Ezt most kimaradt...

**Comment by deseatnikov** [comment]
Lehet majd ezt a poligon gettert úgy megírni, hogy mindig átírja a poligonok pontjait a jelenlegi x és y alapján (ne példányosítsuk újra viszont) vagy az xy+ reference point alapján ha onnan kiindulva vannak megírva és akkor a displaynak majd csak meg kell jeleníteni a poligont és nekem is nagyon, de nagyon segítene a worldmanagerhez

Ehhez akár lehetne egy új poligonutil is, ahol vannak ilyenek: ListShape generateTreePoligoms (Position reference/Position position, ListShape current)

Ha current null akkor létrehozza különben átírja és azt adja vissza

**Comment by kaptast** [comment]
@deseatnikov Az objektumok példányosított (vagy utilból elkért) shape-jét az xy koordináta + referencia pont-al kell majd eltranszformálni és elforgatni, pont mint a rajzolásnál, szóval a getter úgy lesz megírva. A többi pontodat viszont nem nagyon értem, azokat kifejtenéd bővebben?

**Comment by deseatnikov** [comment]
Ha már elforgatva adja vissza a poligonokat akkor semmis, lényegében azt akartam, hogy ne szűréskor kelljen forgatni, mozgatni

**Comment by sandor95** [comment]
Tudjuk, hogy nagyjából mikorra lesz kész ez az issue? Nem szeretnék senkit sürgetni, csak számoljunk legalább annyi idővel, hogy tudja tesztelni a gui csapat és ha hiba van, azt tudjuk majd javítani lehetőleg demo előtt.

**Comment by kaptast** [comment]
A test_world.xml-ben található elemek referenciái kész vannak. Szerintem a teszteléshez egyenlőre elég lesz.

**Comment by sandor95** [comment]
Írtam pár kommentet a PR-hez. Nem muszáj mindent most csinálni, gondold át, mi az, ami maradhat a refakt részre.
