### ISSUE TITLE
Utility model Messages

### ISSUE THREAD

**Issue by deseatnikov** [SzFMV2019-Osz/AutomatedCar-A#57]
package: model.utility

Legyen egy utility class amiben konstant stringek vannak és azokat használjuk error messageshez, hogy ne hardcodeolva legyenek össze-vissza és átírhassuk a messaget és akkor 8 helyen kelljen

(alternatively tárolhatjuk resourceba és akkor akár más nyelvre is lehet fordítani)

- [x] error messagek utilityben
- [x] kódban erre hivatkozás
- [x] world aktualizálás managerhez

**Comment by deseatnikov** [comment]
megcsinálom itt majd a #28-at is

**Comment by deseatnikov** [comment]
@sandor95 kapd le a branchet: f/#57... és kérlek fixáld a teszteket, hogy ne szálljanak el, bár lehet a probléma visszanyúl az objectconverterbe (IObject lista lett a worldObjects)

**Comment by sandor95** [comment]
Javítottam, 2 hibát vétettél, leírom, hogy értsd, mi volt a gond. :)

- a WorldObject imageFileName-t private-ra raktad protectedről -> a JAXB olyan mezőt keresett, ami nem létezett a leszármazottakban (pl. a Tree-ben)
- IObject listet adtál a JAXB-nek, amivel nem tudott mit kezdeni az adapter, ő osztályokkal dolgozik

**Comment by sandor95** [comment]
Ezen kívül 2 meglátásom volt:

- A CommonMessages jó ötlet volt, viszont szerintem jobb név a Consts, át is neveztem. Ha van érved a CommonMessages mellett, akkor csinálunk egy reverse commitot, mert külön commitba került.
- Ha lehetséges, kerüljük a giga commitokat. Nagyon rossz visszakeresni hol is mentek el a dolgok, illetve nehéz rövid, de beszédes messaget írni. Azon túl, ha hiba van és kicsi commitok vannak, akkor könnyebb 1-1 commitot revertálni, mint git historyből előkaparni a régi állapotot.

**Comment by deseatnikov** [comment]
A Consts lehet most jobb név, de amint kerül akármi konstans máshova is már rossz jelentése lesz. És itt azonnal előkerül a másik utility-s class ahol szintén van konstans. A név jó, ha onnan is átmozgatjuk ide a dolgokat, megteszem a worldmanageresben majd. Ha van Consts osztály akkor minden konstans ott legyen szerintem.

Na, itt egy a gond, ha worldobjecttel dolgozunk akkor nagyon leadunk a performanciából, mert a worldmanager IObject listát fog visszaadni és minden szűréskor átcopyzni IObject listába elég gáz lesz. Pont olyan megoldást kerestem, hogy IObject legyen, azt én is sejtettem, hogy ezzel lesz a gond, de azt hittem bedob neki egy WorldObjectet és jó lesz, mert amúgy a lista elfogadja, de úgy látszik nem. Majd a worldmanageresben átcsinálom akkor, hogy legyen egy másik lista ami átveszi ennek tartalmát (csak egyszer) és onnantól csak azt használjuk, mert minden szűréskor átrakosgatni eh.

**Comment by sandor95** [comment]
> A Consts lehet most jobb név, de amint kerül akármi konstans máshova is már rossz jelentése lesz. És itt azonnal előkerül a másik utility-s class ahol szintén van konstans. A név jó, ha onnan is átmozgatjuk ide a dolgokat, megteszem a worldmanageresben majd. Ha van Consts osztály akkor minden konstans ott legyen szerintem.
> 
> A megoldást inkább arra kerestem, hogy IObject listával is meg lehessen oldani és nem azt, hogy vissza legyen írva, de mindegy akkor, megoldom majd a worldmanagerben, hogy ne felezze a performanciát lista másolgatással.

Az nem lesz olyan para, ha nem hívják sűrűn :D Amúgy tök egyszerű, egy lista kell a worldmanagerbe és az inicializálás végén beállítani a listát. Én csak azért oldottam meg így, mert tudtam, hogy úgy is át lesz írva.
