### ISSUE TITLE
Reading keystrokes

### ISSUE THREAD

**Issue by kecsmethy** [SzFMV2019-Osz/AutomatedCar-A#59]

**Comment by bakotamas1997** [comment]
@pintergreg Nekem van egy kérdésem azzal kapcsolatban, hogy virtual function busban lévő loop metódus milyen gyakran fog lefutni? Szükséges nekünk, mivel be kell állítanunk a steppet a különböző Controlloknak(gáz, fék,..).

**Comment by pintergreg** [comment]
@bakotamas1997 A rajzolás miatt azt hiszem 40ms szokott lenni.

**Comment by deseatnikov** [comment]
A releváns PR már bent van, pls closeoljuk a taskokat.
