### ISSUE TITLE
Create Dashboard UI Elements

### ISSUE THREAD

**Issue by kecsmethy** [SzFMV2019-Osz/AutomatedCar-A#65]
Create seperated issues for each element

**Comment by pintergreg** [comment]
Most konkrétan minden egyes gui komponensnek amit fel akartok helyezni a Dashboard panelre külön issue-t akartok létrehozni?
Ráadásul még ha ez tényleg egy ilyen menedzsment taszk, akkor is kéne neki DoD, egy checklistes felsorolással, hogy lehessen tudni, hogy melyek elemekről van szó. 
Továbbá én csapattagként mindenképpen elvárnám, hogy utána ha létrejöttek az issue-k, akkor azok ide legyenek is belinkelve az egyes tételekhez. Nagyjából akkor tudja betölteni a funkcióját ez a taszk. 

Más kérdés, hogy igazából nincs min agyalni, ugyanis a user storyban (#1) elég konkrétan le van írva és látványtervvel meg van támogatva, hogy mit várok. De igazából ez a vegyünk fel egy taszkot arra, hogy vegyünk fel taszkokat eléggé látszatintézkedésnek tűnik, hiszen a user story taszkokra bontása konkrét feladat volt.
