### ISSUE TITLE
Input módosítása, személyesen Team 1- el

### ISSUE THREAD

**Issue by Petyaaaa5** [SzFMV2019-Osz/AutomatedCar-A#70]
Team 1 -el átbeszélni a kormány inputot.

**Comment by pintergreg** [comment]
Itt abba tudnék belekötni, hogy a kormány input megbeszélése, gondolom a paraméter típusa és jelentése miért számít optimalizálásnak.

**Comment by Petyaaaa5** [comment]
Igen teljesen jogos. Valójában már megbeszéltük csak szeretnénk rajta módosítani egy optimálisabb változatra.
