### ISSUE TITLE
Szükséges segédosztályok létrehozása

### ISSUE THREAD

**Issue by Petyaaaa5** [SzFMV2019-Osz/AutomatedCar-A#72]

**Comment by pintergreg** [comment]
Milyen segédosztályok? Mikor van kész ez az issue? Ki fogja megcsinálni és mikorra?

**Comment by Petyaaaa5** [comment]
First 4e88118 

> 
> 
> Milyen segédosztályok? Mikor van kész ez az issue? Ki fogja megcsinálni és mikorra?

**Comment by Petyaaaa5** [comment]
Commit 4e88118 ben alap -Hajtáslánc osztály felvéve.
A többit még nem tudtuk, mik lesznek.

**Comment by pintergreg** [comment]
@Petyaaaa5 A hivatkozott commit nem tartalmaz kódot. Vagy rosszat linkeltél vagy nem ugyanarról beszélünk. 
Ellenben a hivatkozott commit a forráskódhoz ad dokumentációs ábrát. (Ezt én nem fogom a masterbe elfogadni, tehát a team branch-be se kéne eljuttatni.) Éppen a múlt héten hangsúlyozta Laci, hogy ilyet nem csinálunk.
A tervezési ábrát egy issue-be kellett feltölteni. Bármely GH issue/comment esetében drag&drop módon belehúzod a fájt és feltöltésre kerül a GH szerverére. Alternatívaként belinkel tetszőleges drive-ről, képmegosztóról (pl. imgur) linkelni, de ez már majdnem bonyolultabb mint issue-ba csatolni véleményem szerint.

> A többit még nem tudtuk, mik lesznek.
Ez teljesen nyilvánvaló, a Powertrain.png-ből sem következik, hogy milyen osztályaitok lesznek. Viszont ez az issue kiváló felület lehet(ett volna) ennek tisztázására.
