### ISSUE TITLE
[S1] - Display sensor triangle

### ISSUE THREAD

**Issue by arminro** [SzFMV2019-Osz/AutomatedCar-A#73]
DoD:

- [x] a public method exists with parameters for 3 coordinates + 1 color

- [x] a triangle is displayed between the given points

**Comment by pintergreg** [comment]
A fórumrészben kifejtettem, nem kell még szenzor, elég ha ki tudtok rajzolni egy tetszőleges háromszöget.

**Comment by arminro** [comment]
módosítottam a DoD-ot ezek szerint
